import Vue from 'vue'

import {
  Button,
  Icon,
  Image as VanImage,
  NavBar,
  Field,
  Cell,
  CellGroup,
  Toast,
  Checkbox,
  CheckboxGroup,
  Notify,
  Slider,
  Search,
  Swipe,
  SwipeItem,
  Tabbar,
  TabbarItem,
  Popup,
  Picker,
  DatetimePicker,
  Uploader,
  AddressList,
  AddressEdit,
  Area,
  Grid,
  GridItem,
  TreeSelect,
  DropdownMenu,
  DropdownItem,
  Tabs,
  Tab,
  List,
  PullRefresh,
  Card,
  GoodsAction,
  GoodsActionButton,
  GoodsActionIcon,
  Sku,
  Stepper,
  SubmitBar,
  SwipeCell,
  Dialog,
  Col,
  Row,
  CountDown,
  Empty,
  Divider,
  NoticeBar,
  Rate,
  Badge
} from 'vant'

Vue.use(Button)
Vue.use(Icon)
Vue.use(VanImage)
Vue.use(NavBar)
Vue.use(Field)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Toast)
Vue.use(CheckboxGroup)
Vue.use(Checkbox)
Vue.use(Notify)
Vue.use(Slider)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Popup)
Vue.use(Picker)
Vue.use(DatetimePicker)
Vue.use(Uploader)
Vue.use(AddressList)
Vue.use(AddressEdit)
Vue.use(Area)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(TreeSelect)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Card)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(Sku)
Vue.use(Stepper)
Vue.use(SubmitBar)
Vue.use(SwipeCell)
Vue.use(Dialog)
Vue.use(Col)
Vue.use(Row)
Vue.use(CountDown)
Vue.use(Empty)
Vue.use(Divider)
Vue.use(NoticeBar)
Vue.use(Rate)
Vue.use(Badge)
